### ISSUE TITLE
URL to access the builds for project is not working.

### ISSUE THREAD

**Issue by janardhanajl** [jfrog/jenkins-artifactory-plugin#611]
Issue description:
 
Using the Jenkins Artifactory plugin to publish the artifacts to Artifactory, once the Artifacts are published, we receive a URL  in the console output to access the build-in Artifactory. This is not working for the project Builds and throwing a 404 error message.
 
Example:
 
Deploying build info...
Build-info successfully deployed. Browse it in Artifactory under http://myarti.com/ui/builds/jana-pipeline/42/1641643165953/published?project=test
 
 
Steps to Reproduce:
 
1. Push any builds to the Artifactory Project.
2. You will receive an URL in the console output of Jenkins to browse the Artifactory builds  for the project, when you try to access it in the browser you will get a 404 page not found 

**Expected behavior**
 The URL is working outside the project (Global Level) and failing for the project's build, it should be working for the builds published under the project as well.
 
**Screenshots**
 
![image](https://user-images.githubusercontent.com/47290578/148644180-db37c732-9e28-4825-9c07-1352f369b990.png)
![image](https://user-images.githubusercontent.com/47290578/148644197-304411dd-96ad-4fb9-802f-30641e21de40.png)

Environment Details:
 
- Jenkins Artifactory plugin version: 3.15.1
- Artifactory Version: 7.29.8

**Comment by James-Anderson-L3Harris** [comment]
I'm interested to know when this fix will be available.  We want to use projects to separate builds in Artifactory between divisions within our business segment sharing a common instance of Artifactory.  While testing the Artifactory 3.15.1 plugin for Jenkins, I found that while it upload builds to project buildRepos, the links it left behind in Jenkins were invalid.  The invalid links appear in multiple locations.  In the example above, there is an invalid link in the console output.  Interestingly, I don't even see the project= parameter in the URL when uploading to a project, but the 404 response is the same after publishing to a project.  An invalid link is also left behind on the build summary page as well as the badges next to each build on the project/job page in Jenkins classic mode.  In Blue Ocean, I only see it in the console output for the step where the build info is published.  I would like to see it fixed for all those locations.  

I am also interested to know a way to correct the link on build summary pages and badges already created so they direct users to the build where it exists in a projects buildRepo.  Can the latter two be updated in Jenkins?  That fix is presumably outside the scope of the plugin.  It also occurred to me that redirects on the Artifactory side could determine the appropriate buildRepo given a build name, number, and timestamp in the URL.  The AQL can do that.

**Comment by yahavi** [comment]
@janardhanajl,
Thanks for reporting this issue!
Jenkins Artifactory plugin 3.16.0 is released. This version should include the fix for this issue.
We'd appreciate your feedback on that!

**Comment by eyalbe4** [comment]
@James-Anderson-L3Harris,
It sometimes takes a few hours for new releases to become available in Jenkins's update center.

**Comment by James-Anderson-L3Harris** [comment]
We did get the Jenkins Artifactory Plugin 3.16.0 installed in our Jenkins DEV environment.  It was a step in the wrong direction.  We went from Artifactory Build Info links in Jenkins that did not handle projects to those same links just pointing back to the current page in Jenkins where they exist.  The console output went from this:

[](https://cs-dev-jenkins.l3harris.com/job/DevOps/job/MyTestProject/45/console#)[Pipeline] rtPublishBuildInfo
11:39:23  Deploying build info...
11:39:24  Build-info successfully deployed. Browse it in Artifactory under https://cs-artifactorydev.cs.myharris.net/webapp/builds/DevOps%20::%20MyTestProject/45

To this with no link to browse to:

[](https://cs-dev-jenkins.l3harris.com/job/DevOps/job/MyTestProject/47/console#)[Pipeline] rtPublishBuildInfo
14:43:56  Deploying build info...
14:43:56  Build-info successfully deployed.

However, the plugin still creates an Artifactory Build at https://cs-artifactorydev.cs.myharris.net/ui/builds/DevOps%20::%20MyTestProject/47/1647629015804/published?buildRepo=pspc-build-info in this example.

At this point, we have effectively gone from not being able to use projects with the Jenkins Artifactory plugin to not being able to use the latest version of the plugin.

**Comment by yahavi** [comment]
@James-Anderson-L3Harris,
Thank you for reporting the issue.
We’re currently looking into it. We believe that the fix may require a fix on Artifactory, in addition to the new Jenkins Artifactory Plugin patch.
We will send out an update here.

**Comment by James-Anderson-L3Harris** [comment]
Wondering if there is any update on this issue, or what we may have to do on the Artifactory server?  The Jenkins Artifactory Plugin still works fine as long as we are not uploading to Artifactory Project based builds.  It does not include a buildRepo parameter in the URL, but doesn't need to when no project is involved.  For project-based build uploads, the plugin does not provide a URL at all.  Instead, resulting Artifactory links in Jenkins point to the Jenkins page the link is on.  Then, we need to manually navigate to the corresponding Artifactory Build page.

**Comment by yahavi** [comment]
Hi @James-Anderson-L3Harris,
Update - 
The next Artifactory minor release 7.38 will include the needed UI adaptations for your configuration.
Additionally, we released Jenkins Artifactory plugin to 3.16.2 to include https://github.com/jfrog/build-info/pull/631.

**Comment by James-Anderson-L3Harris** [comment]
I got ahold of Artifactory 7.38.7 to use with the Jenkins Artifactory plugin 3.16.2, which I had hoped would resolve this issue producing links to project-based builds in Artifactory, but something is still missing.  The plugin still works fine when no Artifactory project is involved, and it does upload Builds to projects, but still doesn't produce a link to those project-based Builds.  On the Jenkins side, Artifactory Build Info links are empty and point back to the current Jenkins page in the project build cases.  The Builds do exist correctly on the Artifactory side, but still left with a disconnect for the linkage.  Is there something more that needs to be done, either for the plugin or on the Artifactory side to make this work?
